version: '3'
services:
  spark:
    image: lucajanas/spark
    environment:
      - MODE=MASTER
    ports:
      - '8080:8080'
      - '7077:7077'
      - '8888:8888'
    networks:
      spark-network:
        ipv4_address: 172.18.0.22
    volumes:
      - ./load_simulation_data:/data:rw
  spark-worker:
    image: lucajanas/spark
    environment:
      - MODE=WORKER
    networks:
      - spark-network
    volumes:
      - ./load_simulation_data:/data:rw

networks:
  spark-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16